import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import QRCode from "qrcode";

const SUMMIT_URL = "https://summit.commonthreads.org.au/";
const QR_VIEWBOX_UNITS = 45;
const CANVAS_SIZE = 1200;
const CARD_SIZE = 760;
const CARD_OFFSET = (CANVAS_SIZE - CARD_SIZE) / 2;
const QR_SIZE = 640;
const QR_OFFSET = (CANVAS_SIZE - QR_SIZE) / 2;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");
const ctDesignPath = path.join(repoRoot, "public/images/CT_design.svg");
const outputDir = path.join(repoRoot, "public/images/qr");
const simpleOutputPath = path.join(outputDir, "summit-qr-simple.svg");
const brandedOutputPath = path.join(outputDir, "summit-qr.svg");

function extractQrPaths(qrSvg: string): { bgPath: string; modulesPath: string } {
  const matches = qrSvg.match(/<path[^>]*>/g);
  if (!matches || matches.length < 2) {
    throw new Error("Unexpected QR SVG format: expected at least two <path> nodes.");
  }
  const [bgPath, modulesPath] = matches;
  return { bgPath, modulesPath };
}

function toDataUri(svg: string): string {
  return `data:image/svg+xml;base64,${Buffer.from(svg, "utf8").toString("base64")}`;
}

async function main(): Promise<void> {
  await mkdir(outputDir, { recursive: true });

  const qrSvg = await QRCode.toString(SUMMIT_URL, {
    type: "svg",
    errorCorrectionLevel: "H",
    margin: 4,
    color: {
      dark: "#000000",
      light: "#ffffff",
    },
  });

  const ctDesignSvg = await readFile(ctDesignPath, "utf8");
  const ctDesignDataUri = toDataUri(ctDesignSvg);
  const { bgPath, modulesPath } = extractQrPaths(qrSvg);

  const simpleSvg = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-summit-qr.ts -->",
    qrSvg,
  ].join("\n");

  const brandedSvg = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-summit-qr.ts -->
<svg xmlns="http://www.w3.org/2000/svg" width="${CANVAS_SIZE}" height="${CANVAS_SIZE}" viewBox="0 0 ${CANVAS_SIZE} ${CANVAS_SIZE}">
  <defs>
    <mask id="ctBorderMask">
      <rect x="0" y="0" width="${CANVAS_SIZE}" height="${CANVAS_SIZE}" fill="white" />
      <rect x="${CARD_OFFSET - 40}" y="${CARD_OFFSET - 40}" width="${CARD_SIZE + 80}" height="${CARD_SIZE + 80}" rx="72" fill="black" />
    </mask>
  </defs>

  <rect x="0" y="0" width="${CANVAS_SIZE}" height="${CANVAS_SIZE}" fill="#fffdf7" />
  <image
    href="${ctDesignDataUri}"
    x="-80"
    y="-80"
    width="${CANVAS_SIZE + 160}"
    height="${CANVAS_SIZE + 160}"
    preserveAspectRatio="xMidYMid slice"
    opacity="0.34"
    mask="url(#ctBorderMask)"
  />

  <rect x="${CARD_OFFSET}" y="${CARD_OFFSET}" width="${CARD_SIZE}" height="${CARD_SIZE}" rx="52" fill="#ffffff" />
  <rect x="${CARD_OFFSET}" y="${CARD_OFFSET}" width="${CARD_SIZE}" height="${CARD_SIZE}" rx="52" fill="none" stroke="#fca400" stroke-width="6" />

  <g transform="translate(${QR_OFFSET} ${QR_OFFSET}) scale(${QR_SIZE / QR_VIEWBOX_UNITS})" shape-rendering="crispEdges">
    ${bgPath}
    ${modulesPath}
  </g>

  <text x="${CANVAS_SIZE / 2}" y="${CANVAS_SIZE - 105}" text-anchor="middle" font-size="44" font-family="system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif" fill="#111111" font-weight="700">
    Scan for Summit
  </text>
  <text x="${CANVAS_SIZE / 2}" y="${CANVAS_SIZE - 62}" text-anchor="middle" font-size="28" font-family="system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif" fill="#444444">
    summit.commonthreads.org.au
  </text>
</svg>
`;

  await writeFile(simpleOutputPath, simpleSvg, "utf8");
  await writeFile(brandedOutputPath, brandedSvg, "utf8");

  // eslint-disable-next-line no-console
  console.log(`Generated: ${path.relative(repoRoot, simpleOutputPath)}`);
  // eslint-disable-next-line no-console
  console.log(`Generated: ${path.relative(repoRoot, brandedOutputPath)}`);
}

void main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error(error);
  process.exitCode = 1;
});
